### ISSUE TITLE
Episode 3: Setting up a computational project

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#45]
HackMD: https://hackmd.io/@turingway/BJf14ydB9

**Comment by jcolomb** [comment]
- authority argument used too often, especially with PI, one needs a more subtle approach.
- needs a explanation of what is different from a non-computational project, what is data science and what is science.
- Should start with a summary, for example:
```
Tasks:
- Design a online strategy for data sharing (all data should be findable)
- Set up project for team work: describe the vision and plan, set roles, foster documentation
- Computation specificity: RDM, version control, avoid harking/p-hacking
```

? is it the responsability of the PI, what to do if the rest of the team did not follow this course and you are not the PI ?
? what is the advantage to do all that ? what happens if you do not?

Team Framework: too short probably. what does agile mean in research?


Choose a License: this should come later, not necessary at this point. (RDM, openness?)




When saying use a template, link to a template.

Registered Report should be inside reproducibility, maybe as a box?

Documentation needs to be define: document what ? the code, the protocols, the reagents, ...?
