### ISSUE TITLE
Episode 7: Data analysis and results

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#49]
HackMD: https://hackmd.io/@turingway/H1c_ryOB5

**Comment by SaraVilla** [comment]
I've been working on the edited document by [@jafsia elisse](http://www.mboalab.africa/):
https://hackmd.io/nRdzpalNQbmhyoAli5Urpg?both

I made some minor changes/edits till the 'Figures for communication' part and here's some considerations for further review/work in my opinion:

- [ ] in Data analysis section: since different project will have very different pipelines, maybe use this section to illustrate the importance of code annotation and QC during the different bits of analysis? maybe add a hands-on case with a good/bad example of analysis annotation that can be followed or not?
- [ ] Merge Figures for communication and Producing figures?? Maybe insist a bit more on accessibility, since it's something usually overlooked?
- [ ] Merge Data Analysis and Statistical sections? same and in data analysis, maybe just provide the importance of good quality statistical analysis, and redirect to further resources depending on type of analysis done?
- [ ] Communicating results: not sure if this would be related to producing figures or to publication. Either case it seems redundant to me?
- [ ] Resources to take this to the next level: I like this idea. Should we just compile some TuringWay, QC/Statistic basics courses in here? (happy to give it a try)

**Comment by jcolomb** [comment]
comment about data exploration: I strongly disagree with this, data exploration is p-hacking. If you explore the data before choosing your analysis, you bias your analysis toward what looks different.
exploration is only allowed after you did the statistical analysis.

If you need to explore before doing the analysis, you need either fake data, or do the analysis on a different dataset.

**Comment by SaraVilla** [comment]
> 

100% agree with this! I can try to explain it better and move it after the data statistical analysis part, to make this clearer

**Comment by jcolomb** [comment]
will review this
