### ISSUE TITLE
Problem with the GitHub action

### ISSUE THREAD

**Issue by malvikasharan** [carpentries-incubator/managing-computational-projects#64]
Need to see what broke

**Comment by tobyhodges** [comment]
Looking at [the logging output from your Actions](https://github.com/carpentries-incubator/managing-computational-projects/runs/6497335929?check_suite_focus=true), it seems that the problem is with a missing YAML header in [the _GitHub Code Review_ extra page](https://github.com/carpentries-incubator/managing-computational-projects/blob/gh-pages/_extras/09-GithubCodeReview.md?plain=1). I think you will have the same issue with [the similar page on Kanban boards](https://github.com/carpentries-incubator/managing-computational-projects/blob/gh-pages/_extras/08-KanbanTutorial.md?plain=1).

To fix the problem, add a YAML header to these files, e.g.

```
---
title: Page Title Goes Here
---
```
